### ISSUE TITLE
Admin : Can't add from parent if child isn't registered in admin with django 1.7

### ISSUE THREAD

**Issue by fabien-michel** [chrisglass/django_polymorphic#104]
With django 1.7, 
Adding from parent model, after the "child model radio select screen", will crash with the following error if the child model isn't registered in admin : 

Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': 'mychildmodel'}' not found. 1 pattern(s) tried: [u'admin/(?P<app_label>myparentmodel|auth|othermodels|etc)/$']

Do not crash if child model is registered : 

admin.site.register(MyChildModel, MyChildModelAdmin)

This force to register child model while the doc specify this is optional : http://django-polymorphic.readthedocs.org/en/latest/admin.html#example

**Comment by rosco77** [comment]
I'm also getting the same issue

**Comment by jhg-tgu** [comment]
I'm also getting the same issue with Django 1.9.1 and polymorphic in 0.8.1 version, before this work but when update Django and polimorphic it fail.

**Comment by vdboor** [comment]
This should be fixed with django-polymorphic 0.9 now.
