### ISSUE TITLE
ModelForm like admin

### ISSUE THREAD

**Issue by mazing** [chrisglass/django_polymorphic#112]
The admin interface is great. Are there any good examples on how to use django-polymorphic in forms and templates?

**Comment by gilgamezh** [comment]
>If you're looking for an add/edit view that switches the form based on a "Add object type" choice, that's something you could build yourself and share with us!

Any examples/ideas of how to do it?

**Comment by vdboor** [comment]
I'd just display a list of URLs on the first step in HTML, that redirect to the actual form.
You avoid the pain of trying to squeeze a lot of different models in a single formtools wizard.
