### ISSUE TITLE
How can I enforce a purely abstract base class?

### ISSUE THREAD

**Issue by joeyespo** [chrisglass/django_polymorphic#113]
First off, thanks for this project! It's exactly what I was looking for.

As for the question. I have different types of users, all inheriting from a common base.

```python
class User(PolymorphicModel):
    ...

class Foo(User):
    ...

class Bar(User):
    ...
```

However, I'd like to have `User` be purely abstract. That is, that you *cannot* instantiate `User` objects directly, but rather, you can only have `Foo` or `Bar` instances. `User` would be for defining common fields and for querying only. i.e. `User.objects` would return `Foo` and `Bar` objects and never `User` objects.

**Comment by vdboor** [comment]
There is not a standard way to do this, you can however, override the `save` method of the model, and perform some checks there.

**Comment by TheFirstMe** [comment]
@vdboor Is there no other way other than overriding the save method?
