### ISSUE TITLE
RelatedObject is Deprecated in Django >=1.8

### ISSUE THREAD

**Issue by DylanLukes** [chrisglass/django_polymorphic#116]
https://docs.djangoproject.com/en/dev/releases/1.8/#model-field-related

**Comment by DylanLukes** [comment]
It will be removed entirely in Django 2.0.

**Comment by Remiz** [comment]
Anyone else has an issue with the new version 1.8 and this package?

**Comment by unaizalakain** [comment]
I'm getting the same issue with Django 1.8 too.

**Comment by vdboor** [comment]
We've just released django-polymorphic 0.7, which adds Django 1.8 support!

**Comment by Remiz** [comment]
Nice, thank you guys!

**Comment by radlws** [comment]
Excellent, thanks!
