### ISSUE TITLE
unique_together

### ISSUE THREAD

**Issue by variable** [chrisglass/django_polymorphic#123]
I have created a question on SO

http://stackoverflow.com/questions/28799949/django-polymorphic-models-with-unique-together

Someone suggested to use abstract=True but I am not sure if this works properly in this app.

**Comment by hottwaj** [comment]
Here is how I handled this problem.  Bear in mind that I use PostGres as my
database and I do not know if the same problems occur with other databases
(though I guess that they do).

Unique together constraints can only be applied to a single table or view
in PostGres.  This means that out of the box Django/Django-polymorphic
cannot express database-enforced unique constraints on a combination of
fields that are in both a parent table and a child table of Django models
in an inheritance hierarchy.

If you really want database enforced unique constraints on these fields,
you can do one of these two things:
1. copy any parent-model fields that are involved in the unique constraint
into the child's table, and express the unique constraint on the child's
fields and the fields copied from the parent, or
2. create a view on the child that includes both the fields from the parent
and those from the child, and express the unique constraint on this view.

Hope that helps.

**Comment by vdboor** [comment]
Closing per accepted answer on StackOverflow! :+1:

**Comment by paul-axe** [comment]
Sorry for asking, but can you provide more detailed example/explanation of these methods? Seems like first won't work with fields with "related_name" and i don't completely understand second method
