### ISSUE TITLE
Update list_display according to filtered child model

### ISSUE THREAD

**Issue by ayeowch** [chrisglass/django_polymorphic#131]
class ProductAdmin(PolymorphicParentModelAdmin):
        base_model = models.Product
        child_models = (
            (models.Subscription, SubscriptionAdmin),
            (models.Voucher, VoucherAdmin),
        )
        list_filter = (PolymorphicChildModelFilter,)
        list_display = ('thumbnail', 'position',)

Can list_display be made to update itself depending on which child model is selected? For example, when I filter for only Voucher objects, I'd like to be able to have list_display to include additional field for Voucher model instead of just thumbnail and position.

**Comment by vdboor** [comment]
The only way you can do this, is by adding a custom colom as method:

```
    list_display = ('thumbnail', 'position', 'extra_col')

    def extra_col(self, object);
        if isinstance(object, Voucher):
            return object.additional_field
        # or use getattr()
    extra_col.short_description = _("Extra col")
```
