### ISSUE TITLE
'RawSQL' object has no attribute 'source_expressions'

### ISSUE THREAD

**Issue by tyaslab** [chrisglass/django_polymorphic#132]
I found this error when I do aggregation function or other expressions of polymorphic models.

I then changed lines of code in query.py (line no. 106):

                a.source_expressions[0].name = translate_polymorphic_field_path(
                    self.model, a.source_expressions[0].name)

to:

                if hasattr(a, 'source_expressions'):
                    a.source_expressions[0].name = translate_polymorphic_field_path(
                        self.model, a.source_expressions[0].name)

and it works.

**Comment by vdboor** [comment]
I've merged your code of https://github.com/tyaslab/django_polymorphic/commit/9a34a2a5017499bb12512b2387de49aa2c40fc88 and this is now released as django-polymorphic 0.7!
