### ISSUE TITLE
Django 1.8: TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by Remiz** [chrisglass/django_polymorphic#133]
I'm trying to upgrade my project to Django 1.8 and I notice an error that I don't have in 1.7.7.

When I'm calling the Polymorphic objects linked to one of my model I get this error:

```
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I don't know if that's an issue specific to my code but I'll try to post some of relevant parts of my project

```python
class Account(models.Model):
    company = models.CharField(max_length=200)

class BaseQuestion(PolymorphicModel):
    label = models.CharField(max_length=400, null=True, blank=True) 
    position = models.IntegerField(default=0)
    account = models.ForeignKey(Account, related_name='questions')

class QuestionScale(BaseQuestion):
    SCALE_TYPES = (
        (5, '5 stars'),
        (10, '10 stars'),
    )
    scale = models.IntegerField(default=5, choices=SCALE_TYPES)

# Here is the code that trigger the issue
account.questions.all()
```

Did someone else notice similar issue? If needed I can post more details.

Thanks.

**Comment by vdboor** [comment]
I didn't notice this before, but I highly recommend adding a `__str__` or `__unicode__` to your models.
Without the stacktrace and Python version, it's hard to tell why this happens.

**Comment by smcoll** [comment]
@Remiz i've had that issue in other contexts when upgrading to 1.8. In my case, i was using `self.account` in the `__unicode__` method of `BaseQuestion`, and needed to use `self.account.company` instead.

**Comment by Remiz** [comment]
Sorry, I omit to precise the __unicode__ function for my BaseQuestion:

```python
class BaseQuestion(PolymorphicModel):
    label = models.CharField(max_length=400, null=True, blank=True) 
    position = models.IntegerField(default=0)
    account = models.ForeignKey(Account, related_name='questions')
  
    def __unicode__(self):
        return self.label
```

I tried specifying another `__unicode__` for each of my classes inheriting from my `BaseQuestion` but without much success... Still the same error message.It may be related to the fact I'm using django-modeltranslation for that field, so the error may come from the combination of both package, as it's adding another level of complexity to the whole thing.

Thanks for your suggestion @smcoll, but unfortunately it doesn't apply to me as I don't use a foreign value in my `__unicode__`

**Comment by Remiz** [comment]
Interesting findings, if I do:
```python
BaseQuestion.objects.all()
>>>[<QuestionScale: Please rate the speed of service>, <QuestionScale: How would you rate our selection?>, <QuestionScale: How clean are our bathrooms?>...
```
but if I do
```python
BaseQuestion.objects.filter(account=current_account)
*** TypeError: coercing to Unicode: need string or buffer, NoneType found
```
So it seems it's linked to a foreign value issue after all... That's odd.

**Comment by vdboor** [comment]
This can be solved by being more explicit in your code:

```
    def __unicode__(self):
        return unicode(self.label)   # or force_text()
```

**Comment by Remiz** [comment]
Ok, thanks for your help. By using your code I realized that some of my objects return None for label, which isn't normal. Now I'm pretty sure the issue comes from django-modeltranslation.

I'll try to see how it goes for my translated objects that aren't using polymorphic as you suggested.

**Comment by vdboor** [comment]
ok, thanks for letting us know!
