### ISSUE TITLE
Django 1.8 system check prevents polymorphic from working due to clashing fields when using multiple inheritance

### ISSUE THREAD

**Issue by arpheno** [chrisglass/django_polymorphic#136]
In the new system checks framework manage.py won't run any commands when there is a model that inherits from PolymorphicModel twice through parent classes.:

    class A(PolymorphicModel):
        pass
    class B(PolymorphicModel):
        pass
    class C(A,B):
        pass # This will not run

Any idea how to circumvent that issue?

**Comment by vdboor** [comment]
What you're doing here is a diamond-inheritance model. This is something Django never supported, it even broke. We used to have tests for this, but recently those got removed because Django now natively checks it. It doesn't allow this scheme, so if this worked before I'm quite surprised.

**Comment by arpheno** [comment]
It's only diamond shaped in respect to Polymorphic model. If I want
polymorphic models and Multiple Inheritance you're saying it's impossible?

**Comment by arpheno** [comment]
Do you have any comment on the problem ? I can put together an example demonstrating my usecase. I would hate to be pinned down to one version of django.

**Comment by vdboor** [comment]
> It's only diamond shaped in respect to Polymorphic model. 
That is right, but notice how you inherit from 2 concrete classes.

> I downgraded to Django 1.7.8 and now it works beautifully.
Strange. I'm curious what kind of queries it performs.

Also, I think you'll get the same errors if you replace the `PolymorphicModel` with a standard `models.Model`; this warning is not specific to django-polymorphic but rather a Django change.
