### ISSUE TITLE
Please provide docs how to upgrade an existing model 

### ISSUE THREAD

**Issue by guettli** [chrisglass/django_polymorphic#140]
If we change the parent class from `models.Model` to `PolymorphicModel` a new column gets added.

Please give us some hints how to fill the rows which already exist in the database.

Thank you.

**Comment by guettli** [comment]
If you don't fill the column you get this exception:

```

Error
Traceback (most recent call last):
  File "/home/foo_fm_d/src/foo-bar/foo_bar/tests/unit/utils/test_copy_archiv_config.py", line 19, in test_copy_archiv_config
    belegart_for_bar=self.delete_and_create_model_instance(Belegart, name='bar')
  File "/home/foo_fm_d/src/djangotools/djangotools/utils/testutils.py", line 861, in delete_and_create_model_instance
    return delete_and_create_model_instance(model, **kwargs)
  File "/home/foo_fm_d/src/djangotools/djangotools/utils/testutils.py", line 583, in delete_and_create_model_instance
    model.objects.filter(**kwargs).delete()
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/query.py", line 467, in delete
    collector.collect(del_query)
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 196, in collect
    elif sub_objs:
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/query.py", line 100, in __nonzero__
    self._fetch_all()
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/polymorphic/query.py", line 296, in iterator
    real_results = self._get_real_instances(base_result_objects)
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/polymorphic/query.py", line 199, in _get_real_instances
    real_concrete_class = base_object.get_real_instance_class()
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 105, in get_real_instance_class
    model = ContentType.objects.get_for_id(self.polymorphic_ctype_id).model_class()
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 106, in get_for_id
    ct = self.get(pk=id)
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/foo_fm_d/local/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: ContentType matching query does not exist.



```

**Comment by guettli** [comment]
We solved it with this datamigration.

You need this one for every ChildModel:

```
    def forwards(self, orm):
        app_name='foo'
        model_name='ExampleChildModel'
        ct, created = orm['contenttypes.ContentType'].objects.get_or_create(
            model=model_name.lower(), app_label=app_name, defaults=dict(name=model_name))
        for child_instance in orm['%s.%s' % (app_name, model_name)].objects.all():
            child_instance.polymorphic_ctype=ct
            child_instance.save()
```

**Comment by hottwaj** [comment]
This works but the for loop you used will load every object into Django, change one field, then write the object back to the database.  This can be quite slow for big tables!

You can make the database do all the work without loading any objects into Django by using:
orm['%s.%s' % (app_name, model_name)].objects.all().update(polymorphic_ctype = ct)

**Comment by guettli** [comment]
Yes, you are right. Good idea

**Comment by vdboor** [comment]
Great work! (Y) would someone have time to improve the documentation? I'd be happy to accept a PR for it.

**Comment by sheepeatingtaz** [comment]
How can I do this when I am using migrations in django 1.8 and not south? I can only find references to 'orm' in documentation on south, and the djagno documentation here https://docs.djangoproject.com/en/1.8/ref/migration-operations/ to swap `orm["appname", "Model"]` references from South into `apps.get_model("appname", "Model")` doesn't work for me (Granted, I have never tried to write a migration by hand before). My immediate use case means I can just destroy the model and start again, but if this app is as useful as I'm imagining it to be I will want to retroactively apply it to other models too!

**Comment by bbirand** [comment]
:+1:   Also for adding this into the documentation or maybe creating a helper script for updating models that already exist. I'm also on Django 1.8, and I'm trying to do it manually.

**Comment by bbirand** [comment]
OK, after a bit of dabbling, I came up with this method. Let me know if this is makes sense, and whether it makes sense to include this in the documentation:

1. Change the appropriate model's type from `main.models` to `PolymorphicModel`. For this example, let's call our model "MyModel".
2. Run `python manage.py makemigrations`. **DO NOT** apply the migrations yet.
3. Open up the Django shell, and get the primary key `pk` of the appropriate ContentType. Note the name of the contentype is in small case.
```
$ python manage.py shell
>>> from django.contrib.contenttypes.models import ContentType
>>> ContentType.objects.get(model = "mymodel").pk
```
4. Edit the latest migration created in step 2, and find the `AddField

**Comment by TZanke** [comment]
I think this is related to #148 

I don't really understand why it is allowed to have NULL values in polymorphic_ctype.

The issue #148 was closed since null is required during updates. Is this really true?

Please think about it again.

AFAIK you can do updates and supply all needed value during INSERT.

**Comment by vdboor** [comment]
The documention was added: http://django-polymorphic.readthedocs.org/en/latest/migrating.html

@bbirand: I'd prefer setting a proper value based on the model, instead of setting a default.

@TZanke: from a DBA perspective you have a really good point. I do wonder how that works out from a developer point of view - I'd expect to get many tickets from people that the polymorphic_ctype is not defined. In terms of developer-friendlyness I wonder what the best solution will be.

For example, I had to convert a legacy database to a new model, which used polymorphic extensively. Being able to create models without a polymorphic_ctype value set was a great help to fill the base table. Only later during the migration the actual subclasses would be known. Your suggestion (plus letting developers hack the model + migrations) could make complex things near to impossible.

**Comment by TZanke** [comment]
To be safe on the database side, i changed the model classes using polymorphic:

```
class CustomModel(PolymorphicModel):
  ....
CustomModel._meta.get_field('polymorphic_ctype').null = False
```

Making the default behavior null=False, upgrading developers could use the folliwing line while upgrading:
`CustomModel._meta.get_field('polymorphic_ctype').null = True`

(allways execute makemigrations)

After all tables are filled with ctype, remove the line, makemigration, and the database is fine too.

**Comment by guettli** [comment]
I still don't get this statement:

> The polymorphic_ctype can be NULL to ease the migration to polymorphic.

At least in my environment (PostgreSQL) the ForeignKey constraints are "DEFERRABLE INITIALLY DEFERRED".

Example: During a django migration, you can insert new rows which have null values in this column. You just  need to be sure to set the value before the COMMIT.

**Comment by frlan** [comment]
I still think this should be part of polymorphic it self and should work without manual interaction
