### ISSUE TITLE
Is there a type registry?

### ISSUE THREAD

**Issue by guettli** [chrisglass/django_polymorphic#142]
Is there a way to get all child classes of a polymorphic base class?

Example:

```
class Parent(PolymorphicModel):
    pass

class ChildOne(Parent):
    pass

class ChildTwo(Parent):
    pass
```

I need a method which returns `[ChildOne, ChildTwo]`

**Comment by hottwaj** [comment]
I think that you mean you want to introspect the class hierarchy of your models?  If so, the appropriate call is:
MySuperClass.__subclasses__()

This is a standard python method - see here:
http://stackoverflow.com/questions/3862310/how-can-i-find-all-subclasses-of-a-given-class-in-python

**Comment by hottwaj** [comment]
Sorry, I forgot to include appropriate MarkDown - the correct call is: `MySuperClass.__subclasses__()`

**Comment by guettli** [comment]
Yes, I was not aware of that. Thank you for your advice.
