### ISSUE TITLE
Pickle error when caching polymorphic model instance

### ISSUE THREAD

**Issue by svleeuwen** [chrisglass/django_polymorphic#155]
When trying to cache a polymorphic model instance, which is fetched via an annotated queryset, Django raises a Pickle error.

This is caused by the `polymorphic_annotate_names` attribute which is put on the instance here: https://github.com/chrisglass/django_polymorphic/blob/master/polymorphic/query.py#L251

An exception is raised because generators can't be pickled.

A solution would be to just use lists for `polymorphic_annotate_names` and `polymorphic_extra_select_names`.

If needed I can create a simple mockup to reproduce this issue. But it's currently a bit hard to extract out of my application.

**Comment by svleeuwen** [comment]
If you want I can change the generators to lists and create a pull request.

**Comment by vdboor** [comment]
Thanks for the PR!
