### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by jonashaag** [chrisglass/django_polymorphic#166]
Django 1.9 support probably needs multiple small changes here and there, but one of the first issues to be solved is how to deal with Django 1.9's new app loading behaviour. Since Django 1.8, loading models directly or indirectly from an app's `__init__.py` is deprecated. As of Django 1.9, it's not working anymore at all. See this thread: https://groups.google.com/forum/#!topic/django-developers/26GdwpmU6KQ

The `shortcuts` workaround seems like a good idea for me.

I'm happy to come up with a patch.

**Comment by hobarrera** [comment]
I'm rather curious: Is there any reason for *not* defining models in `polymorphic.models`? That would be quite in line with regular django practices, and would fix the issue.

**Comment by jonashaag** [comment]
> I'm rather curious: Is there any reason for not defining models in polymorphic.models? That would be quite in line with regular django practices, and would fix the issue.

It's not only the models; many other parts of django-polymorphic depend on the models being loaded. As an example, the `manager` module depends on the `query` module, which depends on `django.contrib.contenttypes.models.ContentType`.

**Comment by hobarrera** [comment]
Right, but the question still applies: is there any particular reason for not defining Manager and Models in `models.py`, and query in some other file (instead of everything in __init__).

**Comment by lorinkoz** [comment]
Also interested in the outcome of this. Django 1.9 is out there in release candidate stage with some nice features. Wish we could upgrade asap.

**Comment by hobarrera** [comment]
@lorinkoz The linked PR should be ready-for-merge (there seem to be no pending issues on it, merely waiting a response from the devs).

If you can, I'd appreciate you trying out that branch and sending any feedback. :)

**Comment by mvdwaeter** [comment]
What branch is it on? I'd like to test it.

@hobarrera It seems the decision for moving models away from models.py has been made almost 6 years ago 116e2af08b02deed9118a8e71a363ce8b99c9c8e by @bconstantin, perhaps he can explain?

**Comment by hobarrera** [comment]
@mvdwaeter: [PR](#170), [branch](https://github.com/hobarrera/django_polymorphic/tree/django19)

**Comment by eriktelepovsky** [comment]
+1

**Comment by andrewdodd** [comment]
+1

**Comment by mjnaderi** [comment]
I want to upgrade my project to Django 1.9, but it seems a compatible version is not released yet. Can I upgrade to Django 1.9 or should wait for a compatible release? Thanks.

**Comment by hobarrera** [comment]
@mjnaderi There's no stable django19-compatible release yet. I made my own [fork](https://pypi.python.org/pypi/django-polymorphic-ng) temporarily for this (since we **needed** to upgrade), but I otherwise recommend that you wait for a new release.
