### ISSUE TITLE
force_insert=True seems to be ignored

### ISSUE THREAD

**Issue by numjcp** [chrisglass/django_polymorphic#169]
When loading several objects(polymorphic ones), I've noticed that the force_insert=True kwarg in the save method was ignored when inserting data in parents tables. 
The final object is directly inserted (as expected) but the ORM still triggers updates on parents models.
The update fails and then an insert occurs wich is not what I expect.

I guess behavior is the same with force_update.

Regards

**Comment by vdboor** [comment]
This is a standard Django issue, not specific to polymorphic.
