### ISSUE TITLE
clear M2M references

### ISSUE THREAD

**Issue by eriktelepovsky** [chrisglass/django_polymorphic#179]
I have a simple M2M relationship to Polymorphic model ``Product``:

```
class User(AbstractBaseUser, PermissionsMixin):
    products = models.ManyToManyField(Product)
```

When I call ``user.products.clear()`` it works fine, it removes all references from user products.

But when I call ``user.products.instance_of(Membership).clear()`` it raises error:

```
AttributeError: 'PolymorphicQuerySet' object has no attribute 'clear'
```

Right now, I'm using this workaround:

```
for membership in self.products.instance_of(Membership).all():
    self.products.remove(membership)
```

Is there any better solution/fix for this?

**Comment by vdboor** [comment]
The reason this happens is because the M2M fields use `create_many_related_manager()` to subclass the manager. I wonder if the `.clear()` method should still exist after filtering. The `.add()` or other added methods aren't available either.

**Comment by eriktelepovsky** [comment]
I see. Thank you for your answer. Is there any workaround for this? Or do I really need to iterate all queryset as I do now?

**Comment by vdboor** [comment]
You could workaround this by accessing the intermediate M2M table/model, and delete objects there. 

FYI, I view this as a Django feature request rather then a polymorphic bug; to have a `obj.m2m_field.filter(..).clear()` available.
