### ISSUE TITLE
Tiny bug in docs!

### ISSUE THREAD

**Issue by vsoch** [chrisglass/django_polymorphic#180]
This is probably verison specific, but the line [in the docs](https://django-polymorphic.readthedocs.org/en/latest/quickstart.html):

     from polymorphic.models import PolymorphicModel

did not work for me, instead:

      from polymorphic.polymorphic_model import PolymorphicModel

**Comment by vdboor** [comment]
You've seen the new docs for the 0.8 release. It will be out in a few days!

**Comment by vsoch** [comment]
Great, thanks! Happy Holidays :O)
