### ISSUE TITLE
`AppRegistryNotReady` while updating to Django 1.9

### ISSUE THREAD

**Issue by bbirand** [chrisglass/django_polymorphic#187]
I'm trying to upgrade my Django project from 1.8.2 to 1.9.  When I go forward with the upgrade and do `runserver`, I get this error:
```
  File "/code/web/ve/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Since this is a very cryptic error, I figured it was a pretty deep issue. I uncommented every app in my `INSTALLED_APPS`, and started recommenting all of them. The only app that is causing the problem is `django-polymorphic`; when I remove it, the server runs fine.

Did anybody else have this issue? Anybody know how I can try to debug this?

**Comment by 3dingbat** [comment]
Same here

**Comment by tng10** [comment]
I'm using 0.8.1 version with Django 1.9.1 and everything is fine. Are you using the 0.8.1 in polymorphic?

**Comment by luster** [comment]
+1 had this issue on Django 1.9.1 as well

**Comment by vdboor** [comment]
This is caused by pre 0.8 versions, please upgrade polymorphic.
