### ISSUE TITLE
polymorphic_ctype_id empty after adding data in migration

### ISSUE THREAD

**Issue by TZanke** [chrisglass/django_polymorphic#197]
I created a new model based on Django-Polymorphic. Now i try to move data from an other model to the new polymorphic model within a migration.

```
def forwards_func(apps, schema_editor):
    scanable = apps.get_model('xyz', 'Scanable')
    scanable.objects.create(can_scan=xy.for_scan)
```

But after manage.py migrate, the polymorphic_ctype_id column is empty.

What i am doing wrong?

**Comment by TZanke** [comment]
I think i have found the source of the problem:

https://docs.djangoproject.com/es/1.9/topics/migrations/#historical-models

> This means that you will NOT have custom save() methods called on objects when you access them in migrations, and you will NOT have any custom constructors or instance methods. Plan appropriately!

Using Model.objects would work, but this would lead into future problems, if you rely on the history of your models within migrations.

**Comment by vdboor** [comment]
You're not doring anything wrong, but the existing models won't be updated - the value needs to be assigned manually during the migration.

I've added docs for this: http://django-polymorphic.readthedocs.org/en/latest/migrating.html as this get's asked many times in the issue tracker.
