### ISSUE TITLE
Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': 'mychildmodel'}' not found. 1 pattern(s) tried: [u'admin/(?Pmyparentmodel|auth|othermodels|etc)/$']

### ISSUE THREAD

**Issue by jhg-tgu** [chrisglass/django_polymorphic#199]
Reverse for 'app_list' with arguments '()' and keyword arguments '{u'app_label': 'mychildmodel'}' not found. 1 pattern(s) tried: [u'admin/(?Pmyparentmodel|auth|othermodels|etc)/$']

**Comment by vdboor** [comment]
Thanks for reporting this! I've noticed this is a Django 1.9 specific issue, which is worked around in 14a5417891a3e0e378951c92da19c7c23ec029b6.
