### ISSUE TITLE
Is it possible to duplicate element?

### ISSUE THREAD

**Issue by michalwerner** [chrisglass/django_polymorphic#203]
As the first thing I want to say thank you, for brilliant package, for me absolute must have, for bigger projects.
 
Now, the actual question: Is it possible to duplicate polymorphic object? I tried:

```
obj.pk = None
obj.save()
```

but it just saves `obj`, not creating new one.

**Comment by vdboor** [comment]
There is likely a second `basetable_ptr` field lurking somewhere that also holds an ID value. This is not really a polymorphic issue, but rather a Django subclassing topic.
