### ISSUE TITLE
0.9.2 didn't get a .tar.gz uploaded to PyPI correctly

### ISSUE THREAD

**Issue by kwilcox** [chrisglass/django_polymorphic#214]
*shrug*

`0.9.2` - no `.tar.gz`: https://pypi.python.org/pypi/django_polymorphic/0.9.2

`0.9.1` (and all other releases) - has `.tar.gz`: https://pypi.python.org/pypi/django_polymorphic/0.9.1

**Comment by vdboor** [comment]
Fixed! Thanks for reporting this, this likely went wrong due to some connectivity issue while making the release.
