### ISSUE TITLE
PolymorphicModel's __str__

### ISSUE THREAD

**Issue by andgein** [chrisglass/django_polymorphic#219]
I propose to implement default \_\_str\_\_ for PolymorphicModel as follow or something like:

```
def __str__(self):
    instance = self.get_real_instance()
    if self.__str__ != instance.__str__:
         return str(self.get_real_instance())
    return str(super())
```

**Comment by vdboor** [comment]
This would invoke an N-query issue in many applications when they work with non-polymorphic models. I'm not sure this gives such benefit over adding this just in your project base model.
